/* 由 scripts/build-tokens.mjs 產生，請勿手動編輯。 */
/* 值一律是 var(--ds-*)，實際色值由 tokens.css 決定。 */
/* 因此換配色只要動 tokens.css，元件一行都不用改。 */

export const theme = {
  action: {
    accentBgActive: 'var(--ds-action-accent-bg-active)',
    accentBgHover: 'var(--ds-action-accent-bg-hover)',
    accentBg: 'var(--ds-action-accent-bg)',
    accentFocusRing: 'var(--ds-action-accent-focus-ring)',
    accentText: 'var(--ds-action-accent-text)',
    dangerBgActive: 'var(--ds-action-danger-bg-active)',
    dangerBgHover: 'var(--ds-action-danger-bg-hover)',
    dangerBg: 'var(--ds-action-danger-bg)',
    dangerFocusRing: 'var(--ds-action-danger-focus-ring)',
    dangerText: 'var(--ds-action-danger-text)',
    disabledBg: 'var(--ds-action-disabled-bg)',
    disabledBorder: 'var(--ds-action-disabled-border)',
    disabledText: 'var(--ds-action-disabled-text)',
    ghostBgHover: 'var(--ds-action-ghost-bg-hover)',
    ghostFocusRing: 'var(--ds-action-ghost-focus-ring)',
    ghostText: 'var(--ds-action-ghost-text)',
    inverseBgActive: 'var(--ds-action-inverse-bg-active)',
    inverseBgHover: 'var(--ds-action-inverse-bg-hover)',
    inverseBg: 'var(--ds-action-inverse-bg)',
    inverseText: 'var(--ds-action-inverse-text)',
    outlineBorder: 'var(--ds-action-outline-border)',
    primaryBgActive: 'var(--ds-action-primary-bg-active)',
    primaryBgHover: 'var(--ds-action-primary-bg-hover)',
    primaryBg: 'var(--ds-action-primary-bg)',
    primaryFocusRing: 'var(--ds-action-primary-focus-ring)',
    primaryText: 'var(--ds-action-primary-text)',
    secondaryBgActive: 'var(--ds-action-secondary-bg-active)',
    secondaryBgHover: 'var(--ds-action-secondary-bg-hover)',
    secondaryBg: 'var(--ds-action-secondary-bg)',
    secondaryBorder: 'var(--ds-action-secondary-border)',
    secondaryFocusRing: 'var(--ds-action-secondary-focus-ring)',
    secondaryText: 'var(--ds-action-secondary-text)',
  },
  border: {
    accent: 'var(--ds-border-accent)',
    default: 'var(--ds-border-default)',
    disabled: 'var(--ds-border-disabled)',
    editing: 'var(--ds-border-editing)',
    focus: 'var(--ds-border-focus)',
    hover: 'var(--ds-border-hover)',
    subtle: 'var(--ds-border-subtle)',
    inverse: 'var(--ds-border-inverse)',
    widthDefault: 'var(--ds-border-width-default)',
    widthEmphasis: 'var(--ds-border-width-emphasis)',
    widthFocus: 'var(--ds-border-width-focus)',
    widthIcon: 'var(--ds-border-width-icon)',
    widthSelected: 'var(--ds-border-width-selected)',
  },
  brand: {
    primaryActive: 'var(--ds-brand-primary-active)',
    primaryHover: 'var(--ds-brand-primary-hover)',
    primaryTintSubtle: 'var(--ds-brand-primary-tint-subtle)',
    primaryTint: 'var(--ds-brand-primary-tint)',
    primary: 'var(--ds-brand-primary)',
    secondaryActive: 'var(--ds-brand-secondary-active)',
    secondaryHover: 'var(--ds-brand-secondary-hover)',
    secondary: 'var(--ds-brand-secondary)',
  },
  control: {
    circleInlineLg: 'var(--ds-control-circle-inline-lg)',
    circleInlineMd: 'var(--ds-control-circle-inline-md)',
    counterMd: 'var(--ds-control-counter-md)',
    counterSm: 'var(--ds-control-counter-sm)',
    coverMd: 'var(--ds-control-cover-md)',
    dotSm: 'var(--ds-control-dot-sm)',
    height2xs: 'var(--ds-control-height-2xs)',
    heightLg: 'var(--ds-control-height-lg)',
    heightMd: 'var(--ds-control-height-md)',
    heightSm: 'var(--ds-control-height-sm)',
    heightXl: 'var(--ds-control-height-xl)',
    heightXs: 'var(--ds-control-height-xs)',
    textareaMd: 'var(--ds-control-textarea-md)',
    tileMd: 'var(--ds-control-tile-md)',
  },
  feedback: {
    errorDefault: 'var(--ds-feedback-error-default)',
    errorSurface: 'var(--ds-feedback-error-surface)',
    infoDefault: 'var(--ds-feedback-info-default)',
    infoSurface: 'var(--ds-feedback-info-surface)',
    successDefault: 'var(--ds-feedback-success-default)',
    successSurface: 'var(--ds-feedback-success-surface)',
    warningDefault: 'var(--ds-feedback-warning-default)',
    warningSurface: 'var(--ds-feedback-warning-surface)',
  },
  icon: {
    accent: 'var(--ds-icon-accent)',
    default: 'var(--ds-icon-default)',
    disabled: 'var(--ds-icon-disabled)',
    onBrand: 'var(--ds-icon-on-brand)',
    secondary: 'var(--ds-icon-secondary)',
  },
  radius: {
    card: 'var(--ds-radius-card)',
    control: 'var(--ds-radius-control)',
    field: 'var(--ds-radius-field)',
    none: 'var(--ds-radius-none)',
    panel: 'var(--ds-radius-panel)',
    tile: 'var(--ds-radius-tile)',
  },
  size: {
    iconLg: 'var(--ds-size-icon-lg)',
    iconMd: 'var(--ds-size-icon-md)',
    iconSm: 'var(--ds-size-icon-sm)',
  },
  space: {
    gapLg: 'var(--ds-space-gap-lg)',
    gapMd: 'var(--ds-space-gap-md)',
    gapSm: 'var(--ds-space-gap-sm)',
    gapXs: 'var(--ds-space-gap-xs)',
    insetLg: 'var(--ds-space-inset-lg)',
    insetMd: 'var(--ds-space-inset-md)',
    insetSm: 'var(--ds-space-inset-sm)',
    insetXl: 'var(--ds-space-inset-xl)',
    insetXs: 'var(--ds-space-inset-xs)',
    stackLg: 'var(--ds-space-stack-lg)',
    stackMd: 'var(--ds-space-stack-md)',
  },
  surface: {
    brand: 'var(--ds-surface-brand)',
    card: 'var(--ds-surface-card)',
    disabled: 'var(--ds-surface-disabled)',
    inverse: 'var(--ds-surface-inverse)',
    media: 'var(--ds-surface-media)',
    muted: 'var(--ds-surface-muted)',
    page: 'var(--ds-surface-page)',
    raised: 'var(--ds-surface-raised)',
    sunken: 'var(--ds-surface-sunken)',
  },
  text: {
    accent: 'var(--ds-text-accent)',
    disabled: 'var(--ds-text-disabled)',
    onBrand: 'var(--ds-text-on-brand)',
    onInverse: 'var(--ds-text-on-inverse)',
    placeholder: 'var(--ds-text-placeholder)',
    primary: 'var(--ds-text-primary)',
    secondary: 'var(--ds-text-secondary)',
    tertiary: 'var(--ds-text-tertiary)',
  },
  typography: {
    bodyLgLineHeight: 'var(--ds-typography-body-lg-line-height)',
    bodyLgSize: 'var(--ds-typography-body-lg-size)',
    bodyLgWeight: 'var(--ds-typography-body-lg-weight)',
    bodyLineHeight: 'var(--ds-typography-body-line-height)',
    bodySize: 'var(--ds-typography-body-size)',
    bodySmLineHeight: 'var(--ds-typography-body-sm-line-height)',
    bodySmSize: 'var(--ds-typography-body-sm-size)',
    bodySmWeight: 'var(--ds-typography-body-sm-weight)',
    bodyWeight: 'var(--ds-typography-body-weight)',
    captionLineHeight: 'var(--ds-typography-caption-line-height)',
    captionSize: 'var(--ds-typography-caption-size)',
    captionWeight: 'var(--ds-typography-caption-weight)',
    fontDisplay: 'var(--ds-typography-font-display)',
    fontSans: 'var(--ds-typography-font-sans)',
    heading1LineHeight: 'var(--ds-typography-heading-1-line-height)',
    heading1Size: 'var(--ds-typography-heading-1-size)',
    heading1Weight: 'var(--ds-typography-heading-1-weight)',
    heading2LineHeight: 'var(--ds-typography-heading-2-line-height)',
    heading2Size: 'var(--ds-typography-heading-2-size)',
    heading2Weight: 'var(--ds-typography-heading-2-weight)',
    heading3LineHeight: 'var(--ds-typography-heading-3-line-height)',
    heading3Size: 'var(--ds-typography-heading-3-size)',
    heading3Weight: 'var(--ds-typography-heading-3-weight)',
    heading4LineHeight: 'var(--ds-typography-heading-4-line-height)',
    heading4Size: 'var(--ds-typography-heading-4-size)',
    heading4Weight: 'var(--ds-typography-heading-4-weight)',
    labelLineHeight: 'var(--ds-typography-label-line-height)',
    labelSize: 'var(--ds-typography-label-size)',
    labelWeight: 'var(--ds-typography-label-weight)',
    leadLineHeight: 'var(--ds-typography-lead-line-height)',
    leadSize: 'var(--ds-typography-lead-size)',
    leadWeight: 'var(--ds-typography-lead-weight)',
    uiLabelLineHeight: 'var(--ds-typography-ui-label-line-height)',
    uiLabelSize: 'var(--ds-typography-ui-label-size)',
    uiLabelWeight: 'var(--ds-typography-ui-label-weight)',
  },
} as const;

export type Theme = typeof theme;
